name: safe_space
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  socket_io_client: ^2.0.1
  shared_preferences: ^2.0.18
  google_maps_flutter: ^2.2.5
  google_maps_flutter_web: ^0.4.0+7
  location: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/data/Chennai_200_Wards_SafetyData.csv
